# Generated by Django 2.1.5 on 2019-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant', '0002_auto_20190108_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.TextField(blank=True, default='null', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
